module.exports = {
  'accessor-pairs': 'error',
  // ? This might not be a desirable rule at all.
  'arrow-body-style': ['error', 'as-needed'],
  'block-scoped-var': 'error',
  camelcase: 'off',
  'capitalized-comments': 'off',
  'class-methods-use-this': 'error',
  // ? Should this really be a thing? 10 seems like a reasonable place to start
  complexity: ['error', { max: 10 }],
  'consistent-return': ['error', { treatUndefinedAsUnspecified: true }],
  'consistent-this': ['error', 'that'],
  curly: ['error', 'multi-or-nest', 'consistent'],
  'default-case': 'error',
  'default-case-last': 'error',
  'default-param-last': 'error',
  'dot-notation': 'error',
  eqeqeq: 'error',
  'func-name-matching': 'error',
  'func-names': 'error',
  'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
  'grouped-accessor-pairs': 'error',
  'guard-for-in': 'error',
  'id-denylist': 'off',
  // TODO: try and set these to something and see if it's completely annoying
  'id-length': 'off',
  'id-match': 'off',
  'init-declarations': 'off',
  'max-classes-per-file': 'error',
  'max-depth': ['error', { max: 5 }],
  // TODO: enable this in other project to test it out. React files might be a problem.
  'max-lines': 'off',
  'max-lines-per-function': 'off',
  'max-nested-callbacks': ['error', { max: 3 }],
  'max-params': ['error', { max: 3 }],
  'max-statements': 'off',
  'multiline-comment-style': 'error',
  'new-cap': 'error',
  'no-alert': 'error',
  'no-array-constructor': 'error',
  'no-bitwise': 'error',
  'no-caller': 'error',
  'no-case-declarations': 'error',
  'no-confusing-arrow': 'error',
  // Should be disabled for aws-cdk projects, and projects which won't reach the frontend
  'no-console': 'warn',
  'no-continue': 'error',
  'no-delete-var': 'error',
  'no-div-regex': 'error',
  'no-else-return': 'error',
  'no-empty': 'error',
  'no-empty-function': 'error',
  'no-eq-null': 'error',
  'no-eval': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-boolean-cast': 'error',
  'no-extra-boolean-cast': 'error',
  'no-extra-label': 'error',
  'no-extra-semi': 'error',
  'no-floating-decimal': 'error',
  'no-global-assign': 'error',
  'no-implicit-coercion': 'error',
  // ? Does this prevent all function declarations?
  'no-implicit-globals': 'error',
  'no-implied-eval': 'error',
  'no-inline-comments': 'off',
  'no-invalid-this': 'error',
  'no-iterator': 'error',
  'no-label-var': 'error',
  'no-labels': 'error',
  'no-lone-blocks': 'error',
  'no-lonely-if': 'error',
};
